website/models.py
from datetime import datetime
from flask_login import UserMixin
from sqlalchemy import JSON, DateTime
from sqlalchemy.sql import func
from . import db


class CustomSessionModel(db.Model):
    __tablename__: str = "sessions"

    session_id = db.Column(db.String(255), primary_key=True)
    data = db.Column(db.Text)
    expiry = db.Column(db.DateTime)
    modified = db.Column(db.DateTime, default=datetime.utcnow)


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(500))
    price = db.Column(db.Float, nullable=False)
    image_url = db.Column(db.String(200))
    category = db.Column(db.String(100))
    requires_size = db.Column(db.Boolean, default=False)

    sizes = db.relationship("Size", backref="product", cascade="all, delete-orphan")

    favorites = db.relationship(
        "User", secondary="favorites", backref=db.backref("favorites", lazy="dynamic")
    )

    def get_requires_size(self):
        return self.requires_size


class Size(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Integer, db.ForeignKey("product.id"), nullable=False)
    size = db.Column(db.Integer, nullable=False)
    available = db.Column(db.Boolean, nullable=False, default=True)


class CartItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey("product.id"), nullable=False)
    size_id = db.Column(db.Integer, db.ForeignKey("size.id"), nullable=False)
    quantity = db.Column(db.Integer, nullable=False, default=1)


class Favorites(db.Model):
    __tablename__ = "favorites"
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), primary_key=True)
    product_id = db.Column(db.Integer, db.ForeignKey("product.id"), primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship(
        "User", backref=db.backref("favorites_assoc", cascade="all, delete-orphan")
    )

    product = db.relationship(
        "Product", backref=db.backref("users_assoc", cascade="all, delete-orphan")
    )


class UserCartCount(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), unique=True)
    cart_count = db.Column(db.Integer, default=0)


class UserFavoritesCount(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), unique=True)
    favorites_count = db.Column(db.Integer, default=0)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    favorite_products = db.relationship(
        "Product", secondary="favorites", backref=db.backref("users", lazy="dynamic")
    )
    cart_items = db.relationship("CartItem", backref="user", lazy="dynamic")

    def add_to_favorites(self, product) -> None:
        if product not in self.favorite_products:
            self.favorite_products.append(product)

    def has_favorited(self, product) -> bool:
        return product in self.favorites

    def get_favorites_count(self) -> int:
        return Favorites.query.filter_by(user_id=self.id).count()

    def get_favorites(self):
        return self.favorites.all()

    def remove_from_favorites(self, product) -> None:
        if product in self.favorite_products:
            self.favorite_products.remove(product)

    def get_cart_count(self) -> int:
        return CartItem.query.filter_by(user_id=self.id).count()

    def has_cart(self, product) -> bool:
        return product in self.cart_items


class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(255), nullable=False)
    phone = db.Column(db.String(20), nullable=False)
    country = db.Column(db.String(255), nullable=False)
    city = db.Column(db.String(255), nullable=False)
    address = db.Column(db.String(255), nullable=False)
    comment = db.Column(db.Text)
    timestamp = db.Column(DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, nullable=False)
    cart_data = db.Column(JSON)
    total_price = db.Column(db.Float, nullable=False, default=0.0)

    products = db.relationship(
        "Product",
        secondary="order_product",
        backref=db.backref("orders", lazy="dynamic"),
    )


order_product = db.Table(
    "order_product",
    db.Column("order_id", db.Integer, db.ForeignKey("order.id"), primary_key=True),
    db.Column("product_id", db.Integer, db.ForeignKey("product.id"), primary_key=True),
)

website/views.py
from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    session,
)
from flask_login import login_required, current_user, login_user
from sqlalchemy import func
from .models import (
    CartItem,
    Favorites,
    Order,
    Product,
    Size,
    User,
    UserCartCount,
    UserFavoritesCount,
)
from datetime import datetime
import json
import random
from typing import Any, Dict, List, Literal, Optional, Union
from . import db

views = Blueprint("views", __name__)


@views.route("/")
@login_required
def home() -> str:
    products: List[Product] = Product.query.all()
    random.shuffle(products)
    random_products: List[Product] = products[:4]
    sizes: List[Size] = Size.query.all()
    cart_items: List[CartItem] = CartItem.query.filter_by(user_id=current_user.id).all()
    user_cart: List[Dict[str, Any]] = []
    for cart_item in cart_items:
        product = Product.query.get(cart_item.product_id)
        if product:
            item: Dict[str, Any] = {
                "cart_item": cart_item,
                "product": product,
                "quantity": cart_item.quantity,
                "cart_item_id": cart_item.id,
            }
            user_cart.append(item)

    return render_template(
        "base.html",
        user=current_user,
        products=random_products,
        sizes=sizes,
        user_cart=user_cart,
    )


@views.route("/set-language/<lang>")
def set_language(lang) -> Response:
    if lang in ["en", "ru"]:
        session["lang"] = lang
        return redirect(request.referrer or url_for("home"))
    else:
        return redirect(url_for("home"))


@views.route("/cart")
@login_required
def cart() -> str:
    cart_count: int = current_user.get_cart_count()
    cart_items: List[CartItem] = CartItem.query.filter_by(user_id=current_user.id).all()
    user_cart: List[Dict[str, Union[CartItem, Product, str, int]]] = []
    for cart_item in cart_items:
        product: Product = Product.query.get(cart_item.product_id)
        if product:
            size: Size = Size.query.get(cart_item.size_id)
            size_value: Union[str, int] = size.size if size else "0"
            item: Dict[str, Union[CartItem, Product, str, int]] = {
                "cart_item": cart_item,
                "product": product,
                "size": size_value,
                "quantity": cart_item.quantity,
                "cart_item_id": cart_item.id,
            }
            user_cart.append(item)

    return render_template(
        "cart.html", user_cart=user_cart, user=current_user, cart_count=cart_count
    )


@views.route("/favorites")
@login_required
def favorites() -> str:
    favorites_count: int = current_user.get_favorites_count()
    favorites: List[Favorites] = Favorites.query.filter_by(
        user_id=current_user.id
    ).all()
    user_favorites: List[Product] = []

    for favorite in favorites:
        product: Product = Product.query.get(favorite.product_id)
        if product:
            user_favorites.append(product)

    cart_items: List[CartItem] = CartItem.query.filter_by(user_id=current_user.id).all()
    user_cart: List[Dict[str, Any]] = []
    for cart_item in cart_items:
        product: Product = Product.query.get(cart_item.product_id)
        if product:
            size: Size | None = Size.query.get(cart_item.size_id)
            size_value: Any = size.size if size else "0"
            item: Dict[str, Any] = {
                "cart_item": cart_item,
                "product": product,
                "size": size_value,
                "quantity": cart_item.quantity,
                "cart_item_id": cart_item.id,
            }
            user_cart.append(item)

    return render_template(
        "favorites.html",
        favorites_count=favorites_count,
        user_favorites=user_favorites,
        user=current_user,
        user_cart=user_cart,
    )


@views.route("/order")
@login_required
def order() -> str:
    user_orders: List[Order] = Order.query.filter_by(user_id=current_user.id).all()

    processed_orders: List[Dict[str, Any]] = []
    for order in user_orders:
        cart_items = json.loads(order.cart_data)

        processed_order: Dict[str, Any] = {
            "id": order.id,
            "name": order.name,
            "email": order.email,
            "phone": order.phone,
            "country": order.country,
            "comment": order.comment,
            "city": order.city,
            "address": order.address,
            "cart_items": cart_items,
            "total_price": order.total_price,
        }
        processed_orders.append(processed_order)

    return render_template(
        "order.html",
        processed_orders=processed_orders,
        user=current_user,
    )


@views.route("/checkout", methods=["POST", "GET"])
@login_required
def checkout() -> Union[Response, str]:
    if request.method == "POST":
        name: str = request.form.get("name", "")
        email: str = request.form.get("email", "")
        phone: str = request.form.get("phone", "")
        country: str = request.form.get("country", "")
        city: str = request.form.get("city", "")
        address: str = request.form.get("address", "")
        comment: str = request.form.get("comment", "")
        total_price = session.get("total_price")
        cart_items: List[CartItem] = CartItem.query.filter_by(
            user_id=current_user.id
        ).all()
        if not cart_items:
            flash(
                "Your cart is empty. Please add items to your cart before checking out.",
                "warning",
            )
            return redirect(url_for("views.checkout"))

        cart_data: List[Dict[str, Any]] = []
        for cart_item in cart_items:
            product: Product = Product.query.get(cart_item.product_id)
            if product:
                size: Size = Size.query.get(cart_item.size_id)
                size_value: Union[str, int] = size.size if size else "0"
                item: Dict[str, Any] = {
                    "product_id": cart_item.product_id,
                    "name": product.name,
                    "size": size_value,
                    "quantity": cart_item.quantity,
                    "cart_item_id": cart_item.id,
                }
                cart_data.append(item)

        order = Order(
            name=name,
            email=email,
            phone=phone,
            country=country,
            city=city,
            address=address,
            comment=comment,
            timestamp=datetime.now(),
            user_id=current_user.id,
            cart_data=json.dumps(cart_data),
            total_price=total_price,
        )

        db.session.add(order)
        db.session.commit()

        CartItem.query.filter_by(user_id=current_user.id).delete()
        db.session.commit()

        user_cart_count = UserCartCount.query.filter_by(user_id=current_user.id).first()
        if user_cart_count:
            user_cart_count.cart_count = 0
        else:
            user_cart_count = UserCartCount(user_id=current_user.id, cart_count=0)

        db.session.add(user_cart_count)
        db.session.commit()

        session["cart_count"] = 0

        session["total_price"] = 0
        session.pop("total_price", None)
        flash("Your order has been placed successfully!", "success")

        return redirect(url_for("views.home"))
    else:
        cart_items = CartItem.query.filter_by(user_id=current_user.id).all()
        user_cart = []
        for cart_item in cart_items:
            product = Product.query.get(cart_item.product_id)
            if product:
                size = Size.query.get(cart_item.size_id)
                size_value = size.size if size else "0"
                item = {
                    "cart_item": cart_item,
                    "product": product,
                    "size": size_value,
                    "quantity": cart_item.quantity,
                    "cart_item_id": cart_item.id,
                }
                user_cart.append(item)

        return render_template("checkout.html", user=current_user, user_cart=user_cart)


@views.route("/product")
def product_page() -> str:
    if current_user.is_authenticated:
        category: Any = None
        products: List[Product] = Product.query.all()
        sizes: List[Size] = Size.query.all()
        cart_items: List[CartItem] = CartItem.query.filter_by(
            user_id=current_user.id
        ).all()
        user_cart: List[Dict[str, Any]] = []
        for cart_item in cart_items:
            product: Product = Product.query.get(cart_item.product_id)
            if product:
                item: Dict[str, Any] = {
                    "cart_item": cart_item,
                    "product": product,
                    "quantity": cart_item.quantity,
                    "cart_item_id": cart_item.id,
                }
                user_cart.append(item)
        return render_template(
            "product.html",
            products=products,
            sizes=sizes,
            user=current_user,
            category=category,
            user_cart=user_cart,
        )
    else:
        products: List[Product] = Product.query.all()
        sizes: List[Size] = Size.query.all()
        return render_template(
            "product.html", products=products, sizes=sizes, user=None
        )


@views.route("/product/<category>", methods=["GET"])
def category(category: str) -> str:
    products: List[Product] = Product.query.filter_by(category=category).all()
    cart_items: List[CartItem] = CartItem.query.filter_by(user_id=current_user.id).all()
    user_cart: List[Dict[str, Any]] = []
    for cart_item in cart_items:
        product: Product = Product.query.get(cart_item.product_id)
        if product:
            item: Dict[str, Any] = {
                "cart_item": cart_item,
                "product": product,
                "quantity": cart_item.quantity,

website/templates/cart.html
{% extends "base.html" %} {% block hide_carousel %} {% endblock %} {% block
hide_advantages %} {% endblock %} {% block main %}
<main class="main">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8 mb-3">
                <div class="cart-content p-3 h-100 bg-white">
                    <div class="table-responsive">
                        <table class="table align-middle table-hover">
                            <thead>
                                <tr>
                                    <th>Photo</th>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Qty</th>
                                    <th>
                                        <i class="fa-regular fa-trash-can"></i>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in user_cart %}
                                <tr>
                                    <td class="product-img-td">
                                        <a
                                            href="{{url_for('views.product_page')}}"
                                        >
                                            <img
                                                src="{{ item.product.image_url }}"
                                                alt=""
                                                width="150"
                                                height="150"
                                            />
                                        </a>
                                    </td>
                                    <td>
                                        <a
                                            href="{{url_for('views.product_page')}}"
                                            class="cart-content-title"
                                        >
                                            {{ item.product.name }}
                                        </a>
                                        <p>
                                            {% if item.size != "0" %} Size: {{
                                            item.size|default("N/A") }} {% else
                                            %} {% endif %}
                                        </p>
                                    </td>
                                    <td>${{ item.product.price }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>
                                        <form
                                            action="{{ url_for('views.remove_from_cart') }}"
                                            method="POST"
                                        >
                                            <input
                                                type="hidden"
                                                name="cart_item_id"
                                                value="{{ item.cart_item_id }}"
                                            />
                                            <button
                                                class="btn btn-danger"
                                                type="submit"
                                            >
                                                <i
                                                    class="fa-regular fa-circle-xmark"
                                                ></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-3">
                <div class="cart-summary p-3 sidebar">
                    <h5 class="section-title">
                        <span>Cart Summary</span>
                    </h5>

                    <div class="d-flex justify-content-between my-3">
                        <h6>Subtotal</h6>
                        <h6>${{session["total_price"]}}</h6>
                    </div>

                    <div class="d-flex justify-content-between my-3">
                        <h6>Coupon</h6>
                        <h6>$0</h6>
                    </div>

                    <div
                        class="d-flex justify-content-between my-3 border-bottom"
                    >
                        <h6>Shipping</h6>
                        <h6>$0</h6>
                    </div>

                    <button
                        class="btn btn-link px-0 btn-coupon"
                        data-bs-toggle="collapse"
                        data-bs-target="#collapseCoupon"
                    >
                        Have a Coupon?
                    </button>

                    <div class="input-group collapse" id="collapseCoupon">
                        <input
                            type="text"
                            class="form-control"
                            placeholder="Coupon Code"
                        />
                        <button class="btn btn-info">
                            <i class="fa-regular fa-circle-check"></i>
                        </button>
                    </div>

                    <div class="d-flex justify-content-between my-3">
                        <h3>Total</h3>
                        <h3>${{session["total_price"]}}</h3>
                    </div>

                    <div class="d-grid">
                        <a
                            href="{{url_for('views.checkout')}}"
                            class="btn btn-info"
                            >Checkout</a
                        >
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

website/templates/favorites.html
{% extends "base.html" %} {% block hide_carousel %} {% endblock %} {% block
hide_advantages %} {% endblock %} {% block main %}
<section class="featured-products">
    <div class="container-fluid">
        <div class="row mb-5">
            <div class="col-12 text-center">
                <h2 class="section-title">
                    <span style="padding-left: 1rem"> Your likes </span>
                </h2>
            </div>
        </div>
        <div class="row">
            {% for product in user_favorites %}
            <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
                <div class="product-card">
                    <div class="product-thumb">
                        <a href="/product"
                            ><img src="{{ product.image_url }}" alt=""
                        /></a>
                    </div>
                    <div class="product-details">
                        <h4>
                            <a href="/product">{{ product.name }}</a>
                        </h4>
                        <p class="product-excerpt">{{ product.description }}</p>

                        <form
                            action="/add_to_cart"
                            method="post"
                            class="product-form"
                        >
                            <input
                                type="hidden"
                                name="product_id"
                                value="{{ product.id }}"
                            />
                            <div class="product-sizes">
                                {% for size in product.sizes %} {% if
                                size.available %}
                                <button
                                    type="submit"
                                    class="product-size"
                                    name="size_id"
                                    value="{{ size.id }}"
                                >
                                    {{ size.size }}
                                </button>
                                {% else %}
                                <div class="product-size unavailable">
                                    {{ size.size }}
                                </div>
                                {% endif %} {% endfor %}
                            </div>
                        </form>

                        <div
                            class="product-bottom-details d-flex justify-content-between"
                        >
                            <div
                                class="product-price d-flex justify-content-center align-items-center"
                            >
                                ${{ product.price }}
                            </div>
                            <div class="d-flex">
                                <div class="product-links me-2">
                                    <form
                                        action="{{ url_for('views.remove_from_favorites') }}"
                                        method="POST"
                                    >
                                        <input
                                            type="hidden"
                                            name="product_id"
                                            value="{{ product.id }}"
                                        />
                                        <button
                                            type="submit"
                                            class="btn btn-outline-danger remove_from_favorites"
                                        >
                                            <i
                                                class="fa fa-times"
                                                aria-hidden="true"
                                            ></i>
                                        </button>
                                    </form>
                                </div>
                                <div class="product-links">
                                    <form
                                        action="{{ url_for('views.add_to_cart') }}"
                                        method="POST"
                                    >
                                        <input
                                            type="hidden"
                                            name="product_id"
                                            value="{{ product.id }}"
                                        />
                                        <input
                                            type="hidden"
                                            name="size_id"
                                            id="selected-size"
                                            value=""
                                            required
                                        />
                                        <button
                                            type="submit"
                                            class="btn btn-outline-success add-to-cart"
                                        >
                                            <i class="fas fa-shopping-cart"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %} {% block footer %}{% endblock %}

website/templates/mail_verify.html
<!DOCTYPE html>
<html>
    <body>
        <h1>Confirm your account</h1>
        <p>Please click on the link below to confirm your account:</p>
        <a href="{{ confirmation_link }}">Verify account</a>
    </body>
</html>

website/templates/order.html
{% extends "base.html" %} {% block hide_carousel %} {% endblock %} {% block
hide_advantages %} {% endblock %} {% block main %}

<main class="main">
    <div class="container-fluid">
        <div class="row">
            {% for user_order in processed_orders %}
            <div class="col-lg-12 mb-3 product-order-info">
                <div class="Checkout p-3 h-100 bg-white">
                    <h1 class="section-title h3">
                        <span>Order Information</span>
                    </h1>
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label for="name" class="form-label h6">Name</label>
                            <p class="form-control">{{user_order.name}}</p>
                        </div>

                        <div class="col-md-6">
                            <label for="email" class="form-label h6"
                                >Email</label
                            >
                            <p class="form-control">{{user_order.email}}</p>
                        </div>

                        <div class="col-md-6">
                            <label for="phone" class="form-label h6"
                                >Phone</label
                            >
                            <p class="form-control">{{user_order.phone}}</p>
                        </div>

                        <div class="col-md-6">
                            <label for="country" class="form-label h6"
                                >Country</label
                            >
                            <p class="form-control">{{user_order.country}}</p>
                        </div>

                        <div class="col-md-6">
                            <label for="city" class="form-label h6">City</label>
                            <p class="form-control">{{user_order.city}}</p>
                        </div>

                        <div class="col-md-6">
                            <label for="address" class="form-label h6"
                                >Address</label
                            >
                            <p class="form-control">{{user_order.address}}</p>
                        </div>
                        {% if user_order.comment == "" %} {% else %}
                        <div class="col">
                            <label for="comment" class="form-label h6"
                                >Comment</label
                            >
                            <p class="form-control">{{user_order.comment}}</p>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-12 mb-3 product-order-cart">
                <div class="cart-summary p-3 sidebar h-100 bg-white">
                    <h1 class="section-title h3">
                        <span>Products in the order:</span>
                    </h1>

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Size</th>
                                    <th>Quantity</th>
                                    <th class="text-end">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart_item in user_order.cart_items %}
                                <tr>
                                    <td>
                                        <a
                                            href="{{ url_for('views.product_page', product_id=cart_item['product_id']) }}"
                                            class="cart-content-title"
                                        >
                                            {{ cart_item['name'] }}
                                        </a>
                                    </td>
                                    <td>{{ cart_item['size'] }}</td>
                                    <td>{{ cart_item['quantity'] }}</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td colspan="4" class="text-end">
                                        ${{ user_order["total_price"] }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock %}